apiVersion: v1
kind: service
metadata:
    labels:
        service: back_clusterIP
spec:
   type: clusterIP
   selecter:
       matchLabels:
           app: backend
       ports:
         - name: backendports 
           port: 8000
           targetPort: 8000      
