apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip
  labels:
    service: backend_clusterip
spec:
   type: ClusterIP
   selector:
     app: backend
   ports:
     - name: backendports
       port: 8000
       targetPort: 8000
