apiVersion: v1
kind: service
metadata:
    labels:
        service: headless_for_db
spec:
    type: headless
    clusterIP: None
    selector:
        matchLabels:
            app: db
    ports:
      - name: dbports
        port: 5432
        targetPort: 5432