apiVersion: v1
kind: Service
metadata:
  name: headless-db-service              # ✅ Required name
  labels:
    service: headless_for_db
spec:
  type: ClusterIP
  clusterIP: None                        # ✅ Makes it headless
  selector:
    app: db                              # ❗ Don't use matchLabels under selector in Service
  ports:
    - name: dbports
      port: 5432
      targetPort: 5432
