# pvc-db.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteMany # Most databases require exclusive read/write access.
  storageClassName: sc-ebs
  resources:
    requests:
      storage: 10Gi # Requesting 6 GB of storage
