apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-db
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
parameters:
  type: gp3
  fstype: ext4
allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer